### ISSUE TITLE
request help: proxy-rewrite not pass args to upstream

### ISSUE THREAD

**Issue by duzhenxun** [apache/incubator-apisix#880] opened 2019-11-20 02:50 UTC
### Issue description

原API地址为 
http://apis.juhe.cn/ip/ipNew

必传参数是key，ip
最终请求时应是   
http://apis.juhe.cn/ip/ipNew?key=0e989a1f3b24a6b89f865554d4e7fe15&ip=202.101.172.35

现在将此api接入到网关中

```
{
    "value": {
        "upstream_id": "00000000000000000207",
        "plugins": {
            "proxy-rewrite": {
                "host": "apis.juhe.cn",
                "scheme": "http",
                "uri": "/ip/ipNew"
            }
        },
        "uri": "/test",
        "desc": "ip地址"
    },
    "createdIndex": 213,
    "key": "/apisix/routes/00000000000000000204",
    "modifiedIndex": 213
}
```

访问 网关地址：
http://kongadmin.com:29080/test?key=0e989a1f3b24a6b89f865554d4e7fe15&ip=202.101.172.35

发现参数没传过去

**Comment by nature100** [comment] 2019-11-20 07:48
uri末尾加/

**Comment by moonming** [comment] 2019-11-20 08:31
@shuaijinchao please have a look.
I think `proxy-rewrite` should pass `args` to upstream.

**Comment by membphis** [comment] 2019-11-20 09:17
https://github.com/apache/incubator-apisix/blob/master/t/plugin/proxy-rewrite.t#L632

The `proxy-rewrite` pass args to upstream already, the test cases have coverd this case.

**Comment by moonming** [comment] 2019-11-20 09:20
@duzhenxun please provide a reproduce steps.

**Comment by membphis** [comment] 2019-11-20 09:21
@duzhenxun here is my test case, and it passed.

```
=== TEST 20: set route(rewrite uri args)
--- config
    location /t {
        content_by_lua_block {
            local t = require("lib.test_admin").test
            local code, body = t('/apisix/admin/routes/1',
                 ngx.HTTP_PUT,
                 [[{
                        "plugins": {
                            "proxy-rewrite": {
                                "host": "apis.juhe.cn",
                                "scheme": "http",
                                "uri": "/plugin_proxy_rewrite_args",
                                "enable_websocket": false
                            }
                        },
                        "upstream": {
                            "nodes": {
                                "127.0.0.1:1980": 1
                            },
                            "type": "roundrobin"
                        },
                        "uri": "/hello"
                }]]
                )

            if code >= 300 then
                ngx.status = code
            end
            ngx.say(body)
        }
    }
--- request
GET /t
--- response_body
passed
--- no_error_log
[error]



=== TEST 21: rewrite uri args
--- request
GET /hello?key=0e989a1f3b24a6b89f865554d4e7fe15&ip=202.101.172.35
--- response_body
uri: /plugin_proxy_rewrite_args
key: 0e989a1f3b24a6b89f865554d4e7fe15
ip: 202.101.172.35
--- no_error_log
[error]
```

**Comment by shuaijinchao** [comment] 2019-11-20 09:29
@duzhenxun please check the configuration again. this problem has been resolved in PR (#642) and passed the test case.

**Comment by moonming** [comment] 2019-11-20 09:31
I think @duzhenxun maybe using the old version. So please provide the version of APISIX that is important, which will save time.

**Comment by shuaijinchao** [comment] 2019-11-25 06:53
@duzhenxun Can you provide more detailed information? If the problem is caused by the old version, please let us know and close the PR.

**Comment by membphis** [comment] 2020-04-06 02:47
The questioner had no further information and closed it first.

**Closed by membphis** 2020-04-06 02:47 UTC
Labels: bug
